### ISSUE TITLE
Fix for fixed sidebar

### ISSUE THREAD

**Issue by project79** [wolfcms/docs.wolfcms.org#3]
We need to override .bs-sidebar.affix position from "fixed" to "block". I'm not 100% sure but afterwards the sidebar menu should be scrollable.

**Comment by mvdkleijn** [comment]
Doesn't seem to work. However... it seems that our chosen theme will no longer be part of the core mkdocs distribution *and* the readthedocs theme seems to have improved quite a bit. Search now works for example.

I think I'll switch it to the readthedocs theme after some cleanup.

**Comment by project79** [comment]
I see. Sidebar is still fixed. I'll sort it out after you switch theme.

**Comment by mvdkleijn** [comment]
It's up and seems like sidebar is scrollable now. (default settings) What do you think?

**Comment by dajare** [comment]
Better than ever. The previous one had that "won't display enough items" in
(e.g.) the function list. This looks good!

**Comment by mvdkleijn** [comment]
@project79 what do you think? acceptable enough to keep? :smile:

**Comment by project79** [comment]
I'll check it out later when get to my pc.

**Comment by project79** [comment]
I've checked it. Much better IMO. Now we only miss few images. They are missing or path has been changed but that's easy to fix.
